# Archivo: flake.nix
{
  description = "A highly modular Home Manager configuration flake.";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-25.05";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, home-manager, ... }:
    let
      env = import ./env.nix;
      system = env.system;
      pkgs = nixpkgs.legacyPackages.${system};
    in
    {
      homeConfigurations.${env.username} = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;

        # The `modules` list is now generated by our assembler.
        # We import `lib/default.nix` and pass it the dependencies it needs.
        modules = import ./lib {
          # Pass the nixpkgs `lib` for list/string functions.
          lib = nixpkgs.lib;
          # Pass the `env` data for the inline module.
          inherit env;
        };
      };
    };
}